### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by aratonyara** [Ojsholly/virtual-wallet#20]
Hi how are you my friend?

A question does this system have a section for administrator?

To pay money to accounts, view transactions, etc.?

Can this system apply a percentage of commission per transfer?

Greetings.

**Comment by Ojsholly** [comment]
Hello Antonio. It currently does not have those features as I have been
very occupied with other projects. However, I plan to do a cleanup of some
aspects of the project later this year and add some new features such as
the admin portal. Kindly check back regularly to know when that had been
completed. Regards.

**Comment by aratonyara** [comment]
Thanks for answering! Greetings and blessings
